# Generated by Django 4.2 on 2023-04-22 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='folder_path',
            field=models.CharField(default='', max_length=200, verbose_name='موقع مجلد الاجابات'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.FileField(upload_to='2023-04-15-10-49'),
        ),
    ]
