# Generated by Django 4.1.3 on 2023-04-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_exam_folder_path_alter_files_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='folder_path',
        ),
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.FileField(upload_to='2023-04-27-14-48-35'),
        ),
    ]
