# Generated by Django 4.1.3 on 2023-04-27 16:11

from django.db import migrations, models
import django.db.models.deletion
import scanner.models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0004_alter_files_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='files',
        ),
        migrations.AddField(
            model_name='files',
            name='exam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scanner.exam'),
        ),
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.FileField(upload_to=scanner.models.exam_file_path),
        ),
    ]
